### PR TITLE
fix: Fix build of the ms-vscode.js-debug extension

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Build of the `ms-vscode.js-debug` extension is failing with the following error:
```
/ms-vscode.js-debug-src/ms-vscode.js-debug/node_modules/dprint/dprint: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /ms-vscode.js-debug-src/ms-vscode.js-debug/node_modules/dprint/dprint)
```
At the moment:
- `ubi8/nodejs-18:1-102` is used to build the extension.
- `ubi8/nodejs-18:1-102` image contains GLIBC `2.28`
- `ms-vscode.js-debug` requires GLIBC `2.29`

I didn't find `ubi8`-based image with the corresponding `GLIBC` version, 
so I propose to try `ubi9`-based image - it contains `2.34`version.

### CODE REVIEW

**Review by svor — COMMENTED** [review]
I recommend specifying the full image name directly in the Dockerfile as follows:
`FROM registry.access.redhat.com/ubi9/nodejs-20:9.5`

instead of using the `ubi8Image` attribute in `plugin-config.json`. The reason is that you’re using a UBI9 image, but the attribute name still references UBI8, which can cause confusion.

In general I don't remember why devspaces-code uses this Dockerfile to build the extension. Probably @mkuznyetsov should know something about that.

**Comment by RomanNikitenko** [comment]
@svor
I applied your suggestion, thank you for the review!

**Comment by RomanNikitenko** [comment]
@svor
I applied your suggestion, thank you for the review!

**Review by SDawley — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
@svor @SDawley 
Do we still use `devspaces-3-rhel-8`?
or
it make sense to close the current PR and open it for the `devspaces-3-rhel-9` branch?

**Comment by SDawley** [comment]
Should be devspaces-3-rhel-9

**Comment by svor** [comment]
i think you need to make these changes for devspaces-3-rhel-9 and devspaces-3.18-rhel-9

**Review by svor — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
Closing it in favour of:
- https://github.com/redhat-developer/devspaces-vscode-extensions/pull/85
- https://github.com/redhat-developer/devspaces-vscode-extensions/pull/86

**Pull request closed without merging**
